[[constraint]]
  name = "github.com/devopsfaith/krakend"
  version = "0.5"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "go.opencensus.io"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/kpacha/opencensus-influxdb"

[[constraint]]
  branch = "master"
  name = "github.com/census-ecosystem/opencensus-go-exporter-aws"
  
[prune]
  non-go = true
  go-tests = true
  unused-packages = true
